In [ ]:
!pip install pandas
# or pip install pandas in cmd

In [1]:
import pandas as pd

In [2]:
ecom = pd.read_csv('ecommerce_purchase.csv')

In [3]:

ecom.head()

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA
1,1002,C002,Sarah Johnson,sarah.j@email.com,Running Shoes,Fashion,1,79.99,PayPal,2024-01-06,Canada
2,1003,C003,Michael Brown,michael.b@email.com,Bluetooth Speaker,Electronics,1,49.99,Debit Card,2024-01-07,UK
3,1004,C004,Emily Davis,emily.d@email.com,Coffee Maker,Home Appliances,1,89.99,Credit Card,2024-01-08,Australia
4,1005,C005,David Wilson,david.w@email.com,Desk Chair,Furniture,1,129.99,Net Banking,2024-01-09,USA

In [4]:
ecom.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        15 non-null     int64
 1   CustomerID     15 non-null     str
 2   CustomerName   15 non-null     str
 3   Email          15 non-null     str
 4   Product        15 non-null     str
 5   Category       15 non-null     str
 6   Quantity       15 non-null     int64
 7   Price          15 non-null     float64
 8   PaymentMethod  15 non-null     str
 9   PurchaseDate   15 non-null     str
 10  Country        15 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 1.4 KB

In [5]:
ecom.head(2)

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA
1,1002,C002,Sarah Johnson,sarah.j@email.com,Running Shoes,Fashion,1,79.99,PayPal,2024-01-06,Canada

In [6]:
ecom['Price'].mean()
#mean() used for show average values

np.float64(212.72333333333324)

In [7]:
ecom['Price'].max()

np.float64(999.99)

In [8]:
ecom['Price'].min()

np.float64(4.99)

In [11]:
ecom[ecom['Category']=='Fashion'].count()

OrderID          2
CustomerID       2
CustomerName     2
Email            2
Product          2
Category         2
Quantity         2
Price            2
PaymentMethod    2
PurchaseDate     2
Country          2
dtype: int64

In [12]:
ecom.head(1)

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA

In [13]:
ecom[ecom['PaymentMethod'].str.contains("Credit Card")]['PaymentMethod'].count()

np.int64(6)

In [14]:
ecom['Category'].value_counts().head()

Category
Electronics        6
Fashion            2
Home Appliances    2
Furniture          2
Accessories        2
Name: count, dtype: int64

In [15]:
ecom['PaymentMethod'].value_counts().head()

PaymentMethod
Credit Card    6
PayPal         3
Debit Card     3
Net Banking    1
UPI            1
Name: count, dtype: int64

In [16]:
ecom.head(1)

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA

In [17]:
ecom[ecom['Product'] == 'Laptop']['Price']

8    999.99
Name: Price, dtype: float64

In [18]:
ecom[ecom['CustomerID']=='C005']['Email']

4    david.w@email.com
Name: Email, dtype: str

In [19]:
ecom[(ecom['Product']=='Wireless Mouse') & (ecom['Price'] > 5)].count()

OrderID          1
CustomerID       1
CustomerName     1
Email            1
Product          1
Category         1
Quantity         1
Price            1
PaymentMethod    1
PurchaseDate     1
Country          1
dtype: int64

In [ ]:
ecom[ecom['Country'].str.contains("USA")]['Country'].count() #Using str.contains to find the Country USA

In [20]:
#Generate another column with email dominas using str split at the @ element, we keep the domain only
ecom['Email'].str.split("@").str[1]

0     email.com
1     email.com
2     email.com
3     email.com
4     email.com
5     email.com
6     email.com
7     email.com
8     email.com
9     email.com
10    email.com
11    email.com
12    email.com
13    email.com
14    email.com
Name: Email, dtype: object

In [ ]:

ecom.head(1)

In [ ]:
ecom['Email'].value_counts().head()
#ecom['Job'].value_counts().head()